### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages
  commentId: N:TicketShopWebApplication.Pages
  id: TicketShopWebApplication.Pages
  children:
  - TicketShopWebApplication.Pages.AboutModel
  - TicketShopWebApplication.Pages.ContactModel
  - TicketShopWebApplication.Pages.ErrorModel
  - TicketShopWebApplication.Pages.IndexModel
  langs:
  - csharp
  - vb
  name: TicketShopWebApplication.Pages
  nameWithType: TicketShopWebApplication.Pages
  fullName: TicketShopWebApplication.Pages
  type: Namespace
  assemblies:
  - TicketShopWebApplication
references:
- uid: TicketShopWebApplication.Pages.AboutModel
  commentId: T:TicketShopWebApplication.Pages.AboutModel
  isExternal: false
  name: AboutModel
  nameWithType: AboutModel
  fullName: TicketShopWebApplication.Pages.AboutModel
- uid: TicketShopWebApplication.Pages.ContactModel
  commentId: T:TicketShopWebApplication.Pages.ContactModel
  isExternal: false
  name: ContactModel
  nameWithType: ContactModel
  fullName: TicketShopWebApplication.Pages.ContactModel
- uid: TicketShopWebApplication.Pages.ErrorModel
  commentId: T:TicketShopWebApplication.Pages.ErrorModel
  isExternal: false
  name: ErrorModel
  nameWithType: ErrorModel
  fullName: TicketShopWebApplication.Pages.ErrorModel
- uid: TicketShopWebApplication.Pages.IndexModel
  commentId: T:TicketShopWebApplication.Pages.IndexModel
  isExternal: false
  name: IndexModel
  nameWithType: IndexModel
  fullName: TicketShopWebApplication.Pages.IndexModel
