### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  id: ResetPasswordConfirmationModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet
  langs:
  - csharp
  - vb
  name: ResetPasswordConfirmationModel
  nameWithType: ResetPasswordConfirmationModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  type: Class
  source:
    id: ResetPasswordConfirmationModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPasswordConfirmation.cshtml.cs
    startLine: 8
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class ResetPasswordConfirmationModel : PageModel'
    content.vb: >-
      Public Class ResetPasswordConfirmationModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet
  commentId: M:TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet
  id: OnGet
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  langs:
  - csharp
  - vb
  name: OnGet()
  nameWithType: ResetPasswordConfirmationModel.OnGet()
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet()
  type: Method
  source:
    id: OnGet
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPasswordConfirmation.cshtml.cs
    startLine: 10
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public void OnGet()
    content.vb: Public Sub OnGet
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet
  isExternal: false
  name: OnGet
  nameWithType: ResetPasswordConfirmationModel.OnGet
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel.OnGet
