### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  id: ChangePasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  children:
  - TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
  - TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
  - TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
  langs:
  - csharp
  - vb
  name: ChangePasswordModel.InputModel
  nameWithType: ChangePasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ChangePassword.cshtml.cs
    startLine: 35
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
  id: OldPassword
  parent: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: OldPassword
  nameWithType: ChangePasswordModel.InputModel.OldPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
  type: Property
  source:
    id: OldPassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ChangePassword.cshtml.cs
    startLine: 37
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public string OldPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property OldPassword As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
  id: NewPassword
  parent: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: NewPassword
  nameWithType: ChangePasswordModel.InputModel.NewPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
  type: Property
  source:
    id: NewPassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ChangePassword.cshtml.cs
    startLine: 42
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public string NewPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property NewPassword As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
  id: ConfirmPassword
  parent: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: ConfirmPassword
  nameWithType: ChangePasswordModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
  type: Property
  source:
    id: ConfirmPassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ChangePassword.cshtml.cs
    startLine: 48
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public string ConfirmPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConfirmPassword As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
  isExternal: false
  name: OldPassword
  nameWithType: ChangePasswordModel.InputModel.OldPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.OldPassword
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
  isExternal: false
  name: NewPassword
  nameWithType: ChangePasswordModel.InputModel.NewPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.NewPassword
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
  isExternal: false
  name: ConfirmPassword
  nameWithType: ChangePasswordModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel.ConfirmPassword
