### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  id: LoginWith2faModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
  langs:
  - csharp
  - vb
  name: LoginWith2faModel.InputModel
  nameWithType: LoginWith2faModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 31
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
  commentId: P:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
  id: TwoFactorCode
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  langs:
  - csharp
  - vb
  name: TwoFactorCode
  nameWithType: LoginWith2faModel.InputModel.TwoFactorCode
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
  type: Property
  source:
    id: TwoFactorCode
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 33
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string TwoFactorCode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TwoFactorCode As String
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
  commentId: P:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
  id: RememberMachine
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  langs:
  - csharp
  - vb
  name: RememberMachine
  nameWithType: LoginWith2faModel.InputModel.RememberMachine
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
  type: Property
  source:
    id: RememberMachine
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 39
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public bool RememberMachine { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RememberMachine As Boolean
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
  isExternal: false
  name: TwoFactorCode
  nameWithType: LoginWith2faModel.InputModel.TwoFactorCode
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.TwoFactorCode
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
  isExternal: false
  name: RememberMachine
  nameWithType: LoginWith2faModel.InputModel.RememberMachine
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel.RememberMachine
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
