### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  id: ResetPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
  langs:
  - csharp
  - vb
  name: ResetPasswordModel.InputModel
  nameWithType: ResetPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 24
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public class InputModel
    content.vb: Public Class InputModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
  commentId: P:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
  id: Email
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: ResetPasswordModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
  type: Property
  source:
    id: Email
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 26
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: >-
      [Required]

      [EmailAddress]

      public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      <EmailAddress>

      Public Property Email As String
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  - type: System.ComponentModel.DataAnnotations.EmailAddressAttribute
    ctor: System.ComponentModel.DataAnnotations.EmailAddressAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
  commentId: P:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
  id: Password
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: ResetPasswordModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
  type: Property
  source:
    id: Password
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 30
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: >-
      [Required]

      [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]

      [DataType(DataType.Password)]

      public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      <StringLength(100, ErrorMessage:="The {0} must be at least {2} and at max {1} characters long.", MinimumLength:=6)>

      <DataType(DataType.Password)>

      Public Property Password As String
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  - type: System.ComponentModel.DataAnnotations.StringLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.StringLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 100
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: The {0} must be at least {2} and at max {1} characters long.
    - name: MinimumLength
      type: System.Int32
      value: 6
  - type: System.ComponentModel.DataAnnotations.DataTypeAttribute
    ctor: System.ComponentModel.DataAnnotations.DataTypeAttribute.#ctor(System.ComponentModel.DataAnnotations.DataType)
    arguments:
    - type: System.ComponentModel.DataAnnotations.DataType
      value: 11
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
  commentId: P:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
  id: ConfirmPassword
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: ConfirmPassword
  nameWithType: ResetPasswordModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
  type: Property
  source:
    id: ConfirmPassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 35
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: >-
      [DataType(DataType.Password)]

      [Display(Name = "Confirm password")]

      [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]

      public string ConfirmPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <DataType(DataType.Password)>

      <Display(Name:="Confirm password")>

      <Compare("Password", ErrorMessage:="The password and confirmation password do not match.")>

      Public Property ConfirmPassword As String
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword*
  attributes:
  - type: System.ComponentModel.DataAnnotations.DataTypeAttribute
    ctor: System.ComponentModel.DataAnnotations.DataTypeAttribute.#ctor(System.ComponentModel.DataAnnotations.DataType)
    arguments:
    - type: System.ComponentModel.DataAnnotations.DataType
      value: 11
  - type: System.ComponentModel.DataAnnotations.DisplayAttribute
    ctor: System.ComponentModel.DataAnnotations.DisplayAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Name
      type: System.String
      value: Confirm password
  - type: System.ComponentModel.DataAnnotations.CompareAttribute
    ctor: System.ComponentModel.DataAnnotations.CompareAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Password
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: The password and confirmation password do not match.
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
  commentId: P:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
  id: Code
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: Code
  nameWithType: ResetPasswordModel.InputModel.Code
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
  type: Property
  source:
    id: Code
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 40
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Code { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Code As String
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
  isExternal: false
  name: Email
  nameWithType: ResetPasswordModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
  isExternal: false
  name: Password
  nameWithType: ResetPasswordModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Password
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
  isExternal: false
  name: ConfirmPassword
  nameWithType: ResetPasswordModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.ConfirmPassword
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
  isExternal: false
  name: Code
  nameWithType: ResetPasswordModel.InputModel.Code
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel.Code
