### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  id: LoginModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
  - TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
  - TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
  langs:
  - csharp
  - vb
  name: LoginModel.InputModel
  nameWithType: LoginModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Login.cshtml.cs
    startLine: 35
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
  commentId: P:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
  id: Email
  parent: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: LoginModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
  type: Property
  source:
    id: Email
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Login.cshtml.cs
    startLine: 37
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
  commentId: P:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
  id: Password
  parent: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: LoginModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
  type: Property
  source:
    id: Password
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Login.cshtml.cs
    startLine: 41
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
  commentId: P:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
  id: RememberMe
  parent: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  langs:
  - csharp
  - vb
  name: RememberMe
  nameWithType: LoginModel.InputModel.RememberMe
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
  type: Property
  source:
    id: RememberMe
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Login.cshtml.cs
    startLine: 45
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public bool RememberMe { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RememberMe As Boolean
  overload: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
  isExternal: false
  name: Email
  nameWithType: LoginModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
  isExternal: false
  name: Password
  nameWithType: LoginModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.Password
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
  isExternal: false
  name: RememberMe
  nameWithType: LoginModel.InputModel.RememberMe
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel.RememberMe
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
