### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Program
  commentId: T:TicketShopWebApplication.Program
  id: Program
  parent: TicketShopWebApplication
  children:
  - TicketShopWebApplication.Program.BuildWebHost(System.String[])
  - TicketShopWebApplication.Program.Main(System.String[])
  langs:
  - csharp
  - vb
  name: Program
  nameWithType: Program
  fullName: TicketShopWebApplication.Program
  type: Class
  source:
    id: Program
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Program.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication
  syntax:
    content: 'public class Program : object'
    content.vb: >-
      Public Class Program
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Program.Main(System.String[])
  commentId: M:TicketShopWebApplication.Program.Main(System.String[])
  id: Main(System.String[])
  parent: TicketShopWebApplication.Program
  langs:
  - csharp
  - vb
  name: Main(String[])
  nameWithType: Program.Main(String[])
  fullName: TicketShopWebApplication.Program.Main(System.String[])
  type: Method
  source:
    id: Main
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Program.cs
    startLine: 14
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication
  syntax:
    content: public static void Main(string[] args)
    parameters:
    - id: args
      type: System.String[]
    content.vb: Public Shared Sub Main(args As String())
  overload: TicketShopWebApplication.Program.Main*
  nameWithType.vb: Program.Main(String())
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: TicketShopWebApplication.Program.Main(System.String())
  name.vb: Main(String())
- uid: TicketShopWebApplication.Program.BuildWebHost(System.String[])
  commentId: M:TicketShopWebApplication.Program.BuildWebHost(System.String[])
  id: BuildWebHost(System.String[])
  parent: TicketShopWebApplication.Program
  langs:
  - csharp
  - vb
  name: BuildWebHost(String[])
  nameWithType: Program.BuildWebHost(String[])
  fullName: TicketShopWebApplication.Program.BuildWebHost(System.String[])
  type: Method
  source:
    id: BuildWebHost
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Program.cs
    startLine: 19
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication
  syntax:
    content: public static IWebHost BuildWebHost(string[] args)
    parameters:
    - id: args
      type: System.String[]
    return:
      type: IWebHost
    content.vb: Public Shared Function BuildWebHost(args As String()) As IWebHost
  overload: TicketShopWebApplication.Program.BuildWebHost*
  nameWithType.vb: Program.BuildWebHost(String())
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: TicketShopWebApplication.Program.BuildWebHost(System.String())
  name.vb: BuildWebHost(String())
references:
- uid: TicketShopWebApplication
  commentId: N:TicketShopWebApplication
  isExternal: false
  name: TicketShopWebApplication
  nameWithType: TicketShopWebApplication
  fullName: TicketShopWebApplication
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Program.Main*
  commentId: Overload:TicketShopWebApplication.Program.Main
  isExternal: false
  name: Main
  nameWithType: Program.Main
  fullName: TicketShopWebApplication.Program.Main
- uid: System.String[]
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: TicketShopWebApplication.Program.BuildWebHost*
  commentId: Overload:TicketShopWebApplication.Program.BuildWebHost
  isExternal: false
  name: BuildWebHost
  nameWithType: Program.BuildWebHost
  fullName: TicketShopWebApplication.Program.BuildWebHost
- uid: IWebHost
  commentId: '!:IWebHost'
  isExternal: true
  name: IWebHost
  nameWithType: IWebHost
  fullName: IWebHost
