### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  id: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.AccessDeniedModel
  - TicketShopWebApplication.Pages.Account.ConfirmEmailModel
  - TicketShopWebApplication.Pages.Account.ExternalLoginModel
  - TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  - TicketShopWebApplication.Pages.Account.ForgotPasswordConfirmation
  - TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  - TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
  - TicketShopWebApplication.Pages.Account.LockoutModel
  - TicketShopWebApplication.Pages.Account.LoginModel
  - TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  - TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel
  - TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel.InputModel
  - TicketShopWebApplication.Pages.Account.RegisterModel
  - TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  - TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  langs:
  - csharp
  - vb
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
  type: Namespace
  assemblies:
  - TicketShopWebApplication
references:
- uid: TicketShopWebApplication.Pages.Account.AccessDeniedModel
  commentId: T:TicketShopWebApplication.Pages.Account.AccessDeniedModel
  isExternal: false
  name: AccessDeniedModel
  nameWithType: AccessDeniedModel
  fullName: TicketShopWebApplication.Pages.Account.AccessDeniedModel
- uid: TicketShopWebApplication.Pages.Account.ConfirmEmailModel
  commentId: T:TicketShopWebApplication.Pages.Account.ConfirmEmailModel
  isExternal: false
  name: ConfirmEmailModel
  nameWithType: ConfirmEmailModel
  fullName: TicketShopWebApplication.Pages.Account.ConfirmEmailModel
- uid: TicketShopWebApplication.Pages.Account.ExternalLoginModel
  commentId: T:TicketShopWebApplication.Pages.Account.ExternalLoginModel
  isExternal: false
  name: ExternalLoginModel
  nameWithType: ExternalLoginModel
  fullName: TicketShopWebApplication.Pages.Account.ExternalLoginModel
- uid: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: ExternalLoginModel.InputModel
  nameWithType: ExternalLoginModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  isExternal: false
  name: ForgotPasswordModel
  nameWithType: ForgotPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: ForgotPasswordModel.InputModel
  nameWithType: ForgotPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordConfirmation
  commentId: T:TicketShopWebApplication.Pages.Account.ForgotPasswordConfirmation
  isExternal: false
  name: ForgotPasswordConfirmation
  nameWithType: ForgotPasswordConfirmation
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordConfirmation
- uid: TicketShopWebApplication.Pages.Account.LockoutModel
  commentId: T:TicketShopWebApplication.Pages.Account.LockoutModel
  isExternal: false
  name: LockoutModel
  nameWithType: LockoutModel
  fullName: TicketShopWebApplication.Pages.Account.LockoutModel
- uid: TicketShopWebApplication.Pages.Account.LoginModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginModel
  isExternal: false
  name: LoginModel
  nameWithType: LoginModel
  fullName: TicketShopWebApplication.Pages.Account.LoginModel
- uid: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: LoginModel.InputModel
  nameWithType: LoginModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWith2faModel
  isExternal: false
  name: LoginWith2faModel
  nameWithType: LoginWith2faModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: LoginWith2faModel.InputModel
  nameWithType: LoginWith2faModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel
  isExternal: false
  name: LoginWithRecoveryCodeModel
  nameWithType: LoginWithRecoveryCodeModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel
- uid: TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: LoginWithRecoveryCodeModel.InputModel
  nameWithType: LoginWithRecoveryCodeModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWithRecoveryCodeModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.RegisterModel
  commentId: T:TicketShopWebApplication.Pages.Account.RegisterModel
  isExternal: false
  name: RegisterModel
  nameWithType: RegisterModel
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: RegisterModel.InputModel
  nameWithType: RegisterModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordModel
  isExternal: false
  name: ResetPasswordModel
  nameWithType: ResetPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: ResetPasswordModel.InputModel
  nameWithType: ResetPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
  isExternal: false
  name: ResetPasswordConfirmationModel
  nameWithType: ResetPasswordConfirmationModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordConfirmationModel
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
