### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  id: TicketShopWebApplication.Pages.Account.Manage
  children:
  - TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel
  - TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  - TicketShopWebApplication.Pages.Account.Manage.Disable2faModel
  - TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel
  - TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  - TicketShopWebApplication.Pages.Account.Manage.ExternalLoginsModel
  - TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  - TicketShopWebApplication.Pages.Account.Manage.IndexModel
  - TicketShopWebApplication.Pages.Account.Manage.IndexModel.InputModel
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  - TicketShopWebApplication.Pages.Account.Manage.ResetAuthenticatorModel
  - TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel
  - TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel.InputModel
  - TicketShopWebApplication.Pages.Account.Manage.ShowRecoveryCodesModel
  - TicketShopWebApplication.Pages.Account.Manage.TwoFactorAuthenticationModel
  langs:
  - csharp
  - vb
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
  type: Namespace
  assemblies:
  - TicketShopWebApplication
references:
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel
  isExternal: false
  name: ChangePasswordModel
  nameWithType: ChangePasswordModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel
- uid: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: ChangePasswordModel.InputModel
  nameWithType: ChangePasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ChangePasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.Manage.Disable2faModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.Disable2faModel
  isExternal: false
  name: Disable2faModel
  nameWithType: Disable2faModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.Disable2faModel
- uid: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel
  isExternal: false
  name: EnableAuthenticatorModel
  nameWithType: EnableAuthenticatorModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel
- uid: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: EnableAuthenticatorModel.InputModel
  nameWithType: EnableAuthenticatorModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.Manage.ExternalLoginsModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ExternalLoginsModel
  isExternal: false
  name: ExternalLoginsModel
  nameWithType: ExternalLoginsModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ExternalLoginsModel
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  isExternal: false
  name: GenerateRecoveryCodesModel
  nameWithType: GenerateRecoveryCodesModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
- uid: TicketShopWebApplication.Pages.Account.Manage.IndexModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.IndexModel
  isExternal: false
  name: IndexModel
  nameWithType: IndexModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.IndexModel
- uid: TicketShopWebApplication.Pages.Account.Manage.IndexModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.IndexModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: IndexModel.InputModel
  nameWithType: IndexModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.IndexModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  isExternal: false
  name: ManageNavPages
  nameWithType: ManageNavPages
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
- uid: TicketShopWebApplication.Pages.Account.Manage.ResetAuthenticatorModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ResetAuthenticatorModel
  isExternal: false
  name: ResetAuthenticatorModel
  nameWithType: ResetAuthenticatorModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ResetAuthenticatorModel
- uid: TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel
  isExternal: false
  name: SetPasswordModel
  nameWithType: SetPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel
- uid: TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: SetPasswordModel.InputModel
  nameWithType: SetPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.SetPasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.Manage.ShowRecoveryCodesModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ShowRecoveryCodesModel
  isExternal: false
  name: ShowRecoveryCodesModel
  nameWithType: ShowRecoveryCodesModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.ShowRecoveryCodesModel
- uid: TicketShopWebApplication.Pages.Account.Manage.TwoFactorAuthenticationModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.TwoFactorAuthenticationModel
  isExternal: false
  name: TwoFactorAuthenticationModel
  nameWithType: TwoFactorAuthenticationModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.TwoFactorAuthenticationModel
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
