### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  id: ForgotPasswordModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},TicketShopWebApplication.Services.IEmailSender)
  - TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
  - TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync
  langs:
  - csharp
  - vb
  name: ForgotPasswordModel
  nameWithType: ForgotPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  type: Class
  source:
    id: ForgotPasswordModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ForgotPassword.cshtml.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class ForgotPasswordModel : PageModel'
    content.vb: >-
      Public Class ForgotPasswordModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},TicketShopWebApplication.Services.IEmailSender)
  commentId: M:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},TicketShopWebApplication.Services.IEmailSender)
  id: '#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},TicketShopWebApplication.Services.IEmailSender)'
  parent: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  langs:
  - csharp
  - vb
  name: ForgotPasswordModel(UserManager<ApplicationUser>, IEmailSender)
  nameWithType: ForgotPasswordModel.ForgotPasswordModel(UserManager<ApplicationUser>, IEmailSender)
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.ForgotPasswordModel(UserManager<TicketShopWebApplication.Data.ApplicationUser>, TicketShopWebApplication.Services.IEmailSender)
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ForgotPassword.cshtml.cs
    startLine: 17
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IEmailSender emailSender)
    parameters:
    - id: userManager
      type: UserManager{TicketShopWebApplication.Data.ApplicationUser}
    - id: emailSender
      type: TicketShopWebApplication.Services.IEmailSender
    content.vb: Public Sub New(userManager As UserManager(Of ApplicationUser), emailSender As IEmailSender)
  overload: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor*
  nameWithType.vb: ForgotPasswordModel.ForgotPasswordModel(UserManager(Of ApplicationUser), IEmailSender)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.ForgotPasswordModel(UserManager(Of TicketShopWebApplication.Data.ApplicationUser), TicketShopWebApplication.Services.IEmailSender)
  name.vb: ForgotPasswordModel(UserManager(Of ApplicationUser), IEmailSender)
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
  commentId: P:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
  id: Input
  parent: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  langs:
  - csharp
  - vb
  name: Input
  nameWithType: ForgotPasswordModel.Input
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
  type: Property
  source:
    id: Input
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ForgotPassword.cshtml.cs
    startLine: 23
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public ForgotPasswordModel.InputModel Input { get; set; }
    parameters: []
    return:
      type: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
    content.vb: Public Property Input As ForgotPasswordModel.InputModel
  overload: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync
  commentId: M:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync
  id: OnPostAsync
  parent: TicketShopWebApplication.Pages.Account.ForgotPasswordModel
  langs:
  - csharp
  - vb
  name: OnPostAsync()
  nameWithType: ForgotPasswordModel.OnPostAsync()
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync()
  type: Method
  source:
    id: OnPostAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ForgotPassword.cshtml.cs
    startLine: 33
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public Task<IActionResult> OnPostAsync()
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnPostAsync As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.#ctor
  isExternal: false
  name: ForgotPasswordModel
  nameWithType: ForgotPasswordModel.ForgotPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.ForgotPasswordModel
- uid: UserManager{TicketShopWebApplication.Data.ApplicationUser}
  commentId: '!:UserManager{TicketShopWebApplication.Data.ApplicationUser}'
  definition: UserManager`1
  name: UserManager<ApplicationUser>
  nameWithType: UserManager<ApplicationUser>
  fullName: UserManager<TicketShopWebApplication.Data.ApplicationUser>
  nameWithType.vb: UserManager(Of ApplicationUser)
  fullName.vb: UserManager(Of TicketShopWebApplication.Data.ApplicationUser)
  name.vb: UserManager(Of ApplicationUser)
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Services.IEmailSender
  commentId: T:TicketShopWebApplication.Services.IEmailSender
  parent: TicketShopWebApplication.Services
  isExternal: false
  name: IEmailSender
  nameWithType: IEmailSender
  fullName: TicketShopWebApplication.Services.IEmailSender
- uid: UserManager`1
  isExternal: true
  name: UserManager<>
  nameWithType: UserManager<>
  fullName: UserManager<>
  nameWithType.vb: UserManager(Of )
  fullName.vb: UserManager(Of )
  name.vb: UserManager(Of )
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Services
  commentId: N:TicketShopWebApplication.Services
  isExternal: false
  name: TicketShopWebApplication.Services
  nameWithType: TicketShopWebApplication.Services
  fullName: TicketShopWebApplication.Services
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
  isExternal: false
  name: Input
  nameWithType: ForgotPasswordModel.Input
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.Input
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: ForgotPasswordModel.InputModel
  nameWithType: ForgotPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync
  isExternal: false
  name: OnPostAsync
  nameWithType: ForgotPasswordModel.OnPostAsync
  fullName: TicketShopWebApplication.Pages.Account.ForgotPasswordModel.OnPostAsync
- uid: Task{IActionResult}
  commentId: '!:Task{IActionResult}'
  definition: Task`1
  name: Task<IActionResult>
  nameWithType: Task<IActionResult>
  fullName: Task<IActionResult>
  nameWithType.vb: Task(Of IActionResult)
  fullName.vb: Task(Of IActionResult)
  name.vb: Task(Of IActionResult)
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Task`1
  isExternal: true
  name: Task<>
  nameWithType: Task<>
  fullName: Task<>
  nameWithType.vb: Task(Of )
  fullName.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
