### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Services.EmailSender
  commentId: T:TicketShopWebApplication.Services.EmailSender
  id: EmailSender
  parent: TicketShopWebApplication.Services
  children:
  - TicketShopWebApplication.Services.EmailSender.SendEmailAsync(System.String,System.String,System.String)
  langs:
  - csharp
  - vb
  name: EmailSender
  nameWithType: EmailSender
  fullName: TicketShopWebApplication.Services.EmailSender
  type: Class
  source:
    id: EmailSender
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Services\EmailSender.cs
    startLine: 9
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Services
  syntax:
    content: 'public class EmailSender : object, IEmailSender'
    content.vb: >-
      Public Class EmailSender
          Inherits Object
          Implements IEmailSender
  inheritance:
  - System.Object
  implements:
  - TicketShopWebApplication.Services.IEmailSender
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Services.EmailSender.SendEmailAsync(System.String,System.String,System.String)
  commentId: M:TicketShopWebApplication.Services.EmailSender.SendEmailAsync(System.String,System.String,System.String)
  id: SendEmailAsync(System.String,System.String,System.String)
  parent: TicketShopWebApplication.Services.EmailSender
  langs:
  - csharp
  - vb
  name: SendEmailAsync(String, String, String)
  nameWithType: EmailSender.SendEmailAsync(String, String, String)
  fullName: TicketShopWebApplication.Services.EmailSender.SendEmailAsync(System.String, System.String, System.String)
  type: Method
  source:
    id: SendEmailAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Services\EmailSender.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Services
  syntax:
    content: public Task SendEmailAsync(string email, string subject, string message)
    parameters:
    - id: email
      type: System.String
    - id: subject
      type: System.String
    - id: message
      type: System.String
    return:
      type: Task
    content.vb: Public Function SendEmailAsync(email As String, subject As String, message As String) As Task
  overload: TicketShopWebApplication.Services.EmailSender.SendEmailAsync*
  implements:
  - TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String,System.String,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Services
  commentId: N:TicketShopWebApplication.Services
  isExternal: false
  name: TicketShopWebApplication.Services
  nameWithType: TicketShopWebApplication.Services
  fullName: TicketShopWebApplication.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: TicketShopWebApplication.Services.IEmailSender
  commentId: T:TicketShopWebApplication.Services.IEmailSender
  parent: TicketShopWebApplication.Services
  isExternal: false
  name: IEmailSender
  nameWithType: IEmailSender
  fullName: TicketShopWebApplication.Services.IEmailSender
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Services.EmailSender.SendEmailAsync*
  commentId: Overload:TicketShopWebApplication.Services.EmailSender.SendEmailAsync
  isExternal: false
  name: SendEmailAsync
  nameWithType: EmailSender.SendEmailAsync
  fullName: TicketShopWebApplication.Services.EmailSender.SendEmailAsync
- uid: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String,System.String,System.String)
  commentId: M:TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String,System.String,System.String)
  parent: TicketShopWebApplication.Services.IEmailSender
  isExternal: true
  name: SendEmailAsync(String, String, String)
  nameWithType: IEmailSender.SendEmailAsync(String, String, String)
  fullName: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String, System.String, System.String)
  spec.csharp:
  - uid: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String,System.String,System.String)
    name: SendEmailAsync
    nameWithType: IEmailSender.SendEmailAsync
    fullName: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync(System.String,System.String,System.String)
    name: SendEmailAsync
    nameWithType: IEmailSender.SendEmailAsync
    fullName: TicketShopWebApplication.Services.IEmailSender.SendEmailAsync
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Task
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: Task
