### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  id: ExternalLoginModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
  langs:
  - csharp
  - vb
  name: ExternalLoginModel.InputModel
  nameWithType: ExternalLoginModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ExternalLogin.cshtml.cs
    startLine: 40
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
  commentId: P:TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
  id: Email
  parent: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: ExternalLoginModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
  type: Property
  source:
    id: Email
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ExternalLogin.cshtml.cs
    startLine: 42
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
  isExternal: false
  name: Email
  nameWithType: ExternalLoginModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.ExternalLoginModel.InputModel.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
