### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWith2faModel
  id: LoginWith2faModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor(SignInManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel})
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean,System.String)
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync(System.Boolean,System.String)
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
  - TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
  langs:
  - csharp
  - vb
  name: LoginWith2faModel
  nameWithType: LoginWith2faModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  type: Class
  source:
    id: LoginWith2faModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 13
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class LoginWith2faModel : PageModel'
    content.vb: >-
      Public Class LoginWith2faModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor(SignInManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel})
  commentId: M:TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor(SignInManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel})
  id: '#ctor(SignInManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel})'
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: LoginWith2faModel(SignInManager<ApplicationUser>, ILogger<LoginWith2faModel>)
  nameWithType: LoginWith2faModel.LoginWith2faModel(SignInManager<ApplicationUser>, ILogger<LoginWith2faModel>)
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.LoginWith2faModel(SignInManager<TicketShopWebApplication.Data.ApplicationUser>, ILogger<TicketShopWebApplication.Pages.Account.LoginWith2faModel>)
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 18
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public LoginWith2faModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginWith2faModel> logger)
    parameters:
    - id: signInManager
      type: SignInManager{TicketShopWebApplication.Data.ApplicationUser}
    - id: logger
      type: ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel}
    content.vb: Public Sub New(signInManager As SignInManager(Of ApplicationUser), logger As ILogger(Of LoginWith2faModel))
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor*
  nameWithType.vb: LoginWith2faModel.LoginWith2faModel(SignInManager(Of ApplicationUser), ILogger(Of LoginWith2faModel))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: TicketShopWebApplication.Pages.Account.LoginWith2faModel.LoginWith2faModel(SignInManager(Of TicketShopWebApplication.Data.ApplicationUser), ILogger(Of TicketShopWebApplication.Pages.Account.LoginWith2faModel))
  name.vb: LoginWith2faModel(SignInManager(Of ApplicationUser), ILogger(Of LoginWith2faModel))
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
  commentId: P:TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
  id: Input
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: Input
  nameWithType: LoginWith2faModel.Input
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
  type: Property
  source:
    id: Input
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 24
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public LoginWith2faModel.InputModel Input { get; set; }
    parameters: []
    return:
      type: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
    content.vb: Public Property Input As LoginWith2faModel.InputModel
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
  commentId: P:TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
  id: RememberMe
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: RememberMe
  nameWithType: LoginWith2faModel.RememberMe
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
  type: Property
  source:
    id: RememberMe
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 27
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public bool RememberMe { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RememberMe As Boolean
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
  commentId: P:TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
  id: ReturnUrl
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: ReturnUrl
  nameWithType: LoginWith2faModel.ReturnUrl
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
  type: Property
  source:
    id: ReturnUrl
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 29
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string ReturnUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ReturnUrl As String
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean,System.String)
  commentId: M:TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean,System.String)
  id: OnGetAsync(System.Boolean,System.String)
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: OnGetAsync(Boolean, String)
  nameWithType: LoginWith2faModel.OnGetAsync(Boolean, String)
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean, System.String)
  type: Method
  source:
    id: OnGetAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 43
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public Task<IActionResult> OnGetAsync(bool rememberMe, string returnUrl = null)
    parameters:
    - id: rememberMe
      type: System.Boolean
    - id: returnUrl
      type: System.String
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnGetAsync(rememberMe As Boolean, returnUrl As String = Nothing) As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync(System.Boolean,System.String)
  commentId: M:TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync(System.Boolean,System.String)
  id: OnPostAsync(System.Boolean,System.String)
  parent: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  langs:
  - csharp
  - vb
  name: OnPostAsync(Boolean, String)
  nameWithType: LoginWith2faModel.OnPostAsync(Boolean, String)
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync(System.Boolean, System.String)
  type: Method
  source:
    id: OnPostAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\LoginWith2fa.cshtml.cs
    startLine: 59
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public Task<IActionResult> OnPostAsync(bool rememberMe, string returnUrl = null)
    parameters:
    - id: rememberMe
      type: System.Boolean
    - id: returnUrl
      type: System.String
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnPostAsync(rememberMe As Boolean, returnUrl As String = Nothing) As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.#ctor
  isExternal: false
  name: LoginWith2faModel
  nameWithType: LoginWith2faModel.LoginWith2faModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.LoginWith2faModel
- uid: SignInManager{TicketShopWebApplication.Data.ApplicationUser}
  commentId: '!:SignInManager{TicketShopWebApplication.Data.ApplicationUser}'
  definition: SignInManager`1
  name: SignInManager<ApplicationUser>
  nameWithType: SignInManager<ApplicationUser>
  fullName: SignInManager<TicketShopWebApplication.Data.ApplicationUser>
  nameWithType.vb: SignInManager(Of ApplicationUser)
  fullName.vb: SignInManager(Of TicketShopWebApplication.Data.ApplicationUser)
  name.vb: SignInManager(Of ApplicationUser)
  spec.csharp:
  - uid: SignInManager`1
    name: SignInManager
    nameWithType: SignInManager
    fullName: SignInManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: SignInManager`1
    name: SignInManager
    nameWithType: SignInManager
    fullName: SignInManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: )
    nameWithType: )
    fullName: )
- uid: ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel}
  commentId: '!:ILogger{TicketShopWebApplication.Pages.Account.LoginWith2faModel}'
  definition: ILogger`1
  name: ILogger<LoginWith2faModel>
  nameWithType: ILogger<LoginWith2faModel>
  fullName: ILogger<TicketShopWebApplication.Pages.Account.LoginWith2faModel>
  nameWithType.vb: ILogger(Of LoginWith2faModel)
  fullName.vb: ILogger(Of TicketShopWebApplication.Pages.Account.LoginWith2faModel)
  name.vb: ILogger(Of LoginWith2faModel)
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel
    name: LoginWith2faModel
    nameWithType: LoginWith2faModel
    fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel
    name: LoginWith2faModel
    nameWithType: LoginWith2faModel
    fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel
  - name: )
    nameWithType: )
    fullName: )
- uid: SignInManager`1
  isExternal: true
  name: SignInManager<>
  nameWithType: SignInManager<>
  fullName: SignInManager<>
  nameWithType.vb: SignInManager(Of )
  fullName.vb: SignInManager(Of )
  name.vb: SignInManager(Of )
  spec.csharp:
  - uid: SignInManager`1
    name: SignInManager
    nameWithType: SignInManager
    fullName: SignInManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: SignInManager`1
    name: SignInManager
    nameWithType: SignInManager
    fullName: SignInManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: ILogger`1
  isExternal: true
  name: ILogger<>
  nameWithType: ILogger<>
  fullName: ILogger<>
  nameWithType.vb: ILogger(Of )
  fullName.vb: ILogger(Of )
  name.vb: ILogger(Of )
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
  isExternal: false
  name: Input
  nameWithType: LoginWith2faModel.Input
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.Input
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: LoginWith2faModel.InputModel
  nameWithType: LoginWith2faModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
  isExternal: false
  name: RememberMe
  nameWithType: LoginWith2faModel.RememberMe
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.RememberMe
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
  isExternal: false
  name: ReturnUrl
  nameWithType: LoginWith2faModel.ReturnUrl
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.ReturnUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync
  isExternal: false
  name: OnGetAsync
  nameWithType: LoginWith2faModel.OnGetAsync
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnGetAsync
- uid: Task{IActionResult}
  commentId: '!:Task{IActionResult}'
  definition: Task`1
  name: Task<IActionResult>
  nameWithType: Task<IActionResult>
  fullName: Task<IActionResult>
  nameWithType.vb: Task(Of IActionResult)
  fullName.vb: Task(Of IActionResult)
  name.vb: Task(Of IActionResult)
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Task`1
  isExternal: true
  name: Task<>
  nameWithType: Task<>
  fullName: Task<>
  nameWithType.vb: Task(Of )
  fullName.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync
  isExternal: false
  name: OnPostAsync
  nameWithType: LoginWith2faModel.OnPostAsync
  fullName: TicketShopWebApplication.Pages.Account.LoginWith2faModel.OnPostAsync
