### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  id: ManageNavPages
  parent: TicketShopWebApplication.Pages.Account.Manage
  children:
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass(ViewContext)
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass(ViewContext)
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass(ViewContext)
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass(ViewContext,System.String)
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
  - TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)
  langs:
  - csharp
  - vb
  name: ManageNavPages
  nameWithType: ManageNavPages
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  type: Class
  source:
    id: ManageNavPages
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 8
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: 'public static class ManageNavPages : object'
    content.vb: >-
      Public Module ManageNavPages
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
  id: Index
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: Index
  nameWithType: ManageNavPages.Index
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
  type: Property
  source:
    id: Index
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 10
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string Index { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property Index As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
  id: ChangePassword
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: ChangePassword
  nameWithType: ManageNavPages.ChangePassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
  type: Property
  source:
    id: ChangePassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string ChangePassword { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property ChangePassword As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
  id: ExternalLogins
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: ExternalLogins
  nameWithType: ManageNavPages.ExternalLogins
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
  type: Property
  source:
    id: ExternalLogins
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 14
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string ExternalLogins { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property ExternalLogins As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
  id: TwoFactorAuthentication
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: TwoFactorAuthentication
  nameWithType: ManageNavPages.TwoFactorAuthentication
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
  type: Property
  source:
    id: TwoFactorAuthentication
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 16
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string TwoFactorAuthentication { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property TwoFactorAuthentication As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass(ViewContext)
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass(ViewContext)
  id: IndexNavClass(ViewContext)
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: IndexNavClass(ViewContext)
  nameWithType: ManageNavPages.IndexNavClass(ViewContext)
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass(ViewContext)
  type: Method
  source:
    id: IndexNavClass
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 18
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string IndexNavClass(ViewContext viewContext)
    parameters:
    - id: viewContext
      type: ViewContext
    return:
      type: System.String
    content.vb: Public Shared Function IndexNavClass(viewContext As ViewContext) As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass(ViewContext)
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass(ViewContext)
  id: ChangePasswordNavClass(ViewContext)
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: ChangePasswordNavClass(ViewContext)
  nameWithType: ManageNavPages.ChangePasswordNavClass(ViewContext)
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass(ViewContext)
  type: Method
  source:
    id: ChangePasswordNavClass
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 20
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string ChangePasswordNavClass(ViewContext viewContext)
    parameters:
    - id: viewContext
      type: ViewContext
    return:
      type: System.String
    content.vb: Public Shared Function ChangePasswordNavClass(viewContext As ViewContext) As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass(ViewContext)
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass(ViewContext)
  id: ExternalLoginsNavClass(ViewContext)
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: ExternalLoginsNavClass(ViewContext)
  nameWithType: ManageNavPages.ExternalLoginsNavClass(ViewContext)
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass(ViewContext)
  type: Method
  source:
    id: ExternalLoginsNavClass
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 22
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string ExternalLoginsNavClass(ViewContext viewContext)
    parameters:
    - id: viewContext
      type: ViewContext
    return:
      type: System.String
    content.vb: Public Shared Function ExternalLoginsNavClass(viewContext As ViewContext) As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)
  id: TwoFactorAuthenticationNavClass(ViewContext)
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: TwoFactorAuthenticationNavClass(ViewContext)
  nameWithType: ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)
  type: Method
  source:
    id: TwoFactorAuthenticationNavClass
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 24
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string TwoFactorAuthenticationNavClass(ViewContext viewContext)
    parameters:
    - id: viewContext
      type: ViewContext
    return:
      type: System.String
    content.vb: Public Shared Function TwoFactorAuthenticationNavClass(viewContext As ViewContext) As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass(ViewContext,System.String)
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass(ViewContext,System.String)
  id: PageNavClass(ViewContext,System.String)
  parent: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages
  langs:
  - csharp
  - vb
  name: PageNavClass(ViewContext, String)
  nameWithType: ManageNavPages.PageNavClass(ViewContext, String)
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass(ViewContext, System.String)
  type: Method
  source:
    id: PageNavClass
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\ManageNavPages.cs
    startLine: 26
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public static string PageNavClass(ViewContext viewContext, string page)
    parameters:
    - id: viewContext
      type: ViewContext
    - id: page
      type: System.String
    return:
      type: System.String
    content.vb: Public Shared Function PageNavClass(viewContext As ViewContext, page As String) As String
  overload: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
  isExternal: false
  name: Index
  nameWithType: ManageNavPages.Index
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.Index
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
  isExternal: false
  name: ChangePassword
  nameWithType: ManageNavPages.ChangePassword
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePassword
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
  isExternal: false
  name: ExternalLogins
  nameWithType: ManageNavPages.ExternalLogins
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLogins
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
  isExternal: false
  name: TwoFactorAuthentication
  nameWithType: ManageNavPages.TwoFactorAuthentication
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthentication
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass
  isExternal: false
  name: IndexNavClass
  nameWithType: ManageNavPages.IndexNavClass
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.IndexNavClass
- uid: ViewContext
  isExternal: true
  name: ViewContext
  nameWithType: ViewContext
  fullName: ViewContext
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass
  isExternal: false
  name: ChangePasswordNavClass
  nameWithType: ManageNavPages.ChangePasswordNavClass
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ChangePasswordNavClass
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass
  isExternal: false
  name: ExternalLoginsNavClass
  nameWithType: ManageNavPages.ExternalLoginsNavClass
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.ExternalLoginsNavClass
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass
  isExternal: false
  name: TwoFactorAuthenticationNavClass
  nameWithType: ManageNavPages.TwoFactorAuthenticationNavClass
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.TwoFactorAuthenticationNavClass
- uid: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass
  isExternal: false
  name: PageNavClass
  nameWithType: ManageNavPages.PageNavClass
  fullName: TicketShopWebApplication.Pages.Account.Manage.ManageNavPages.PageNavClass
