### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  id: EnableAuthenticatorModel.InputModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  children:
  - TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
  langs:
  - csharp
  - vb
  name: EnableAuthenticatorModel.InputModel
  nameWithType: EnableAuthenticatorModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\EnableAuthenticator.cshtml.cs
    startLine: 41
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
  commentId: P:TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
  id: Code
  parent: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel
  langs:
  - csharp
  - vb
  name: Code
  nameWithType: EnableAuthenticatorModel.InputModel.Code
  fullName: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
  type: Property
  source:
    id: Code
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\EnableAuthenticator.cshtml.cs
    startLine: 43
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public string Code { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Code As String
  overload: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
  isExternal: false
  name: Code
  nameWithType: EnableAuthenticatorModel.InputModel.Code
  fullName: TicketShopWebApplication.Pages.Account.Manage.EnableAuthenticatorModel.InputModel.Code
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
