### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  commentId: T:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  id: CreateIdentitySchema
  parent: TicketShopWebApplication.Data.Migrations
  children:
  - TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel(ModelBuilder)
  - TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down(MigrationBuilder)
  - TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up(MigrationBuilder)
  langs:
  - csharp
  - vb
  name: CreateIdentitySchema
  nameWithType: CreateIdentitySchema
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  type: Class
  source:
    id: CreateIdentitySchema
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\Migrations\00000000000000_CreateIdentitySchema.Designer.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data.Migrations
  syntax:
    content: 'public class CreateIdentitySchema : Migration'
    content.vb: >-
      Public Class CreateIdentitySchema
          Inherits Migration
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up(MigrationBuilder)
  commentId: M:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up(MigrationBuilder)
  id: Up(MigrationBuilder)
  parent: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  langs:
  - csharp
  - vb
  name: Up(MigrationBuilder)
  nameWithType: CreateIdentitySchema.Up(MigrationBuilder)
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up(MigrationBuilder)
  type: Method
  source:
    id: Up
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\Migrations\00000000000000_CreateIdentitySchema.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data.Migrations
  syntax:
    content: protected override void Up(MigrationBuilder migrationBuilder)
    parameters:
    - id: migrationBuilder
      type: MigrationBuilder
    content.vb: Protected Overrides Sub Up(migrationBuilder As MigrationBuilder)
  overload: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down(MigrationBuilder)
  commentId: M:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down(MigrationBuilder)
  id: Down(MigrationBuilder)
  parent: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  langs:
  - csharp
  - vb
  name: Down(MigrationBuilder)
  nameWithType: CreateIdentitySchema.Down(MigrationBuilder)
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down(MigrationBuilder)
  type: Method
  source:
    id: Down
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\Migrations\00000000000000_CreateIdentitySchema.cs
    startLine: 194
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data.Migrations
  syntax:
    content: protected override void Down(MigrationBuilder migrationBuilder)
    parameters:
    - id: migrationBuilder
      type: MigrationBuilder
    content.vb: Protected Overrides Sub Down(migrationBuilder As MigrationBuilder)
  overload: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel(ModelBuilder)
  commentId: M:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel(ModelBuilder)
  id: BuildTargetModel(ModelBuilder)
  parent: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema
  langs:
  - csharp
  - vb
  name: BuildTargetModel(ModelBuilder)
  nameWithType: CreateIdentitySchema.BuildTargetModel(ModelBuilder)
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel(ModelBuilder)
  type: Method
  source:
    id: BuildTargetModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\Migrations\00000000000000_CreateIdentitySchema.Designer.cs
    startLine: 15
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data.Migrations
  syntax:
    content: protected override void BuildTargetModel(ModelBuilder modelBuilder)
    parameters:
    - id: modelBuilder
      type: ModelBuilder
    content.vb: Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
  overload: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
references:
- uid: TicketShopWebApplication.Data.Migrations
  commentId: N:TicketShopWebApplication.Data.Migrations
  isExternal: false
  name: TicketShopWebApplication.Data.Migrations
  nameWithType: TicketShopWebApplication.Data.Migrations
  fullName: TicketShopWebApplication.Data.Migrations
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up*
  commentId: Overload:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up
  isExternal: false
  name: Up
  nameWithType: CreateIdentitySchema.Up
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Up
- uid: MigrationBuilder
  isExternal: true
  name: MigrationBuilder
  nameWithType: MigrationBuilder
  fullName: MigrationBuilder
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down*
  commentId: Overload:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down
  isExternal: false
  name: Down
  nameWithType: CreateIdentitySchema.Down
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.Down
- uid: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel*
  commentId: Overload:TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel
  isExternal: false
  name: BuildTargetModel
  nameWithType: CreateIdentitySchema.BuildTargetModel
  fullName: TicketShopWebApplication.Data.Migrations.CreateIdentitySchema.BuildTargetModel
- uid: ModelBuilder
  isExternal: true
  name: ModelBuilder
  nameWithType: ModelBuilder
  fullName: ModelBuilder
