### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Services.EmailSenderExtensions
  commentId: T:TicketShopWebApplication.Services.EmailSenderExtensions
  id: EmailSenderExtensions
  parent: TicketShopWebApplication.Services
  children:
  - TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  - TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  langs:
  - csharp
  - vb
  name: EmailSenderExtensions
  nameWithType: EmailSenderExtensions
  fullName: TicketShopWebApplication.Services.EmailSenderExtensions
  type: Class
  source:
    id: EmailSenderExtensions
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Extensions\EmailSenderExtensions.cs
    startLine: 9
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Services
  syntax:
    content: public static class EmailSenderExtensions
    content.vb: Public Module EmailSenderExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  commentId: M:TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  id: SendEmailConfirmationAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  isExtensionMethod: true
  parent: TicketShopWebApplication.Services.EmailSenderExtensions
  langs:
  - csharp
  - vb
  name: SendEmailConfirmationAsync(IEmailSender, String, String)
  nameWithType: EmailSenderExtensions.SendEmailConfirmationAsync(IEmailSender, String, String)
  fullName: TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync(TicketShopWebApplication.Services.IEmailSender, System.String, System.String)
  type: Method
  source:
    id: SendEmailConfirmationAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Extensions\EmailSenderExtensions.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Services
  syntax:
    content: public static Task SendEmailConfirmationAsync(this IEmailSender emailSender, string email, string link)
    parameters:
    - id: emailSender
      type: TicketShopWebApplication.Services.IEmailSender
    - id: email
      type: System.String
    - id: link
      type: System.String
    return:
      type: System.Threading.Tasks.Task
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function SendEmailConfirmationAsync(emailSender As IEmailSender, email As String, link As String) As Task
  overload: TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  commentId: M:TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  id: SendResetPasswordAsync(TicketShopWebApplication.Services.IEmailSender,System.String,System.String)
  isExtensionMethod: true
  parent: TicketShopWebApplication.Services.EmailSenderExtensions
  langs:
  - csharp
  - vb
  name: SendResetPasswordAsync(IEmailSender, String, String)
  nameWithType: EmailSenderExtensions.SendResetPasswordAsync(IEmailSender, String, String)
  fullName: TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync(TicketShopWebApplication.Services.IEmailSender, System.String, System.String)
  type: Method
  source:
    id: SendResetPasswordAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Extensions\EmailSenderExtensions.cs
    startLine: 17
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Services
  syntax:
    content: public static Task SendResetPasswordAsync(this IEmailSender emailSender, string email, string callbackUrl)
    parameters:
    - id: emailSender
      type: TicketShopWebApplication.Services.IEmailSender
    - id: email
      type: System.String
    - id: callbackUrl
      type: System.String
    return:
      type: System.Threading.Tasks.Task
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function SendResetPasswordAsync(emailSender As IEmailSender, email As String, callbackUrl As String) As Task
  overload: TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: TicketShopWebApplication.Services
  commentId: N:TicketShopWebApplication.Services
  isExternal: false
  name: TicketShopWebApplication.Services
  nameWithType: TicketShopWebApplication.Services
  fullName: TicketShopWebApplication.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync*
  commentId: Overload:TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync
  isExternal: false
  name: SendEmailConfirmationAsync
  nameWithType: EmailSenderExtensions.SendEmailConfirmationAsync
  fullName: TicketShopWebApplication.Services.EmailSenderExtensions.SendEmailConfirmationAsync
- uid: TicketShopWebApplication.Services.IEmailSender
  commentId: T:TicketShopWebApplication.Services.IEmailSender
  parent: TicketShopWebApplication.Services
  isExternal: false
  name: IEmailSender
  nameWithType: IEmailSender
  fullName: TicketShopWebApplication.Services.IEmailSender
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync*
  commentId: Overload:TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync
  isExternal: false
  name: SendResetPasswordAsync
  nameWithType: EmailSenderExtensions.SendResetPasswordAsync
  fullName: TicketShopWebApplication.Services.EmailSenderExtensions.SendResetPasswordAsync
