### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  id: RegisterModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
  - TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
  - TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
  langs:
  - csharp
  - vb
  name: RegisterModel.InputModel
  nameWithType: RegisterModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  type: Class
  source:
    id: InputModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Register.cshtml.cs
    startLine: 38
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class InputModel : object'
    content.vb: >-
      Public Class InputModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
  commentId: P:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
  id: Email
  parent: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: RegisterModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
  type: Property
  source:
    id: Email
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Register.cshtml.cs
    startLine: 40
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
  commentId: P:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
  id: Password
  parent: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: RegisterModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
  type: Property
  source:
    id: Password
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Register.cshtml.cs
    startLine: 45
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
  commentId: P:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
  id: ConfirmPassword
  parent: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel
  langs:
  - csharp
  - vb
  name: ConfirmPassword
  nameWithType: RegisterModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
  type: Property
  source:
    id: ConfirmPassword
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Register.cshtml.cs
    startLine: 51
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public string ConfirmPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConfirmPassword As String
  overload: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email*
  commentId: Overload:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
  isExternal: false
  name: Email
  nameWithType: RegisterModel.InputModel.Email
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password*
  commentId: Overload:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
  isExternal: false
  name: Password
  nameWithType: RegisterModel.InputModel.Password
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.Password
- uid: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword*
  commentId: Overload:TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
  isExternal: false
  name: ConfirmPassword
  nameWithType: RegisterModel.InputModel.ConfirmPassword
  fullName: TicketShopWebApplication.Pages.Account.RegisterModel.InputModel.ConfirmPassword
