### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Controllers.HomeController
  commentId: T:TicketShopWebApplication.Controllers.HomeController
  id: HomeController
  parent: TicketShopWebApplication.Controllers
  children:
  - TicketShopWebApplication.Controllers.HomeController.Create
  - TicketShopWebApplication.Controllers.HomeController.Create(IFormCollection)
  - TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32)
  - TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32,IFormCollection)
  - TicketShopWebApplication.Controllers.HomeController.Details(System.Int32)
  - TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32)
  - TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32,IFormCollection)
  - TicketShopWebApplication.Controllers.HomeController.Index
  langs:
  - csharp
  - vb
  name: HomeController
  nameWithType: HomeController
  fullName: TicketShopWebApplication.Controllers.HomeController
  type: Class
  source:
    id: HomeController
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 9
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: 'public class HomeController : Controller'
    content.vb: >-
      Public Class HomeController
          Inherits Controller
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Controllers.HomeController.Index
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Index
  id: Index
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Index()
  nameWithType: HomeController.Index()
  fullName: TicketShopWebApplication.Controllers.HomeController.Index()
  type: Method
  source:
    id: Index
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 13
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Index()
    return:
      type: ActionResult
    content.vb: Public Function Index As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Index*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Details(System.Int32)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Details(System.Int32)
  id: Details(System.Int32)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Details(Int32)
  nameWithType: HomeController.Details(Int32)
  fullName: TicketShopWebApplication.Controllers.HomeController.Details(System.Int32)
  type: Method
  source:
    id: Details
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 19
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Details(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: ActionResult
    content.vb: Public Function Details(id As Integer) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Details*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Create
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Create
  id: Create
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Create()
  nameWithType: HomeController.Create()
  fullName: TicketShopWebApplication.Controllers.HomeController.Create()
  type: Method
  source:
    id: Create
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 25
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Create()
    return:
      type: ActionResult
    content.vb: Public Function Create As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Create*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Create(IFormCollection)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Create(IFormCollection)
  id: Create(IFormCollection)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Create(IFormCollection)
  nameWithType: HomeController.Create(IFormCollection)
  fullName: TicketShopWebApplication.Controllers.HomeController.Create(IFormCollection)
  type: Method
  source:
    id: Create
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 31
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Create(IFormCollection collection)
    parameters:
    - id: collection
      type: IFormCollection
    return:
      type: ActionResult
    content.vb: Public Function Create(collection As IFormCollection) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Create*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32)
  id: Edit(System.Int32)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Edit(Int32)
  nameWithType: HomeController.Edit(Int32)
  fullName: TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32)
  type: Method
  source:
    id: Edit
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 48
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Edit(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: ActionResult
    content.vb: Public Function Edit(id As Integer) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Edit*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32,IFormCollection)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32,IFormCollection)
  id: Edit(System.Int32,IFormCollection)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Edit(Int32, IFormCollection)
  nameWithType: HomeController.Edit(Int32, IFormCollection)
  fullName: TicketShopWebApplication.Controllers.HomeController.Edit(System.Int32, IFormCollection)
  type: Method
  source:
    id: Edit
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 54
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Edit(int id, IFormCollection collection)
    parameters:
    - id: id
      type: System.Int32
    - id: collection
      type: IFormCollection
    return:
      type: ActionResult
    content.vb: Public Function Edit(id As Integer, collection As IFormCollection) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Edit*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32)
  id: Delete(System.Int32)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Delete(Int32)
  nameWithType: HomeController.Delete(Int32)
  fullName: TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32)
  type: Method
  source:
    id: Delete
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 71
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Delete(int id)
    parameters:
    - id: id
      type: System.Int32
    return:
      type: ActionResult
    content.vb: Public Function Delete(id As Integer) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Delete*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32,IFormCollection)
  commentId: M:TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32,IFormCollection)
  id: Delete(System.Int32,IFormCollection)
  parent: TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: Delete(Int32, IFormCollection)
  nameWithType: HomeController.Delete(Int32, IFormCollection)
  fullName: TicketShopWebApplication.Controllers.HomeController.Delete(System.Int32, IFormCollection)
  type: Method
  source:
    id: Delete
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Controllers\HomeController.cs
    startLine: 77
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Controllers
  syntax:
    content: public ActionResult Delete(int id, IFormCollection collection)
    parameters:
    - id: id
      type: System.Int32
    - id: collection
      type: IFormCollection
    return:
      type: ActionResult
    content.vb: Public Function Delete(id As Integer, collection As IFormCollection) As ActionResult
  overload: TicketShopWebApplication.Controllers.HomeController.Delete*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Controllers
  commentId: N:TicketShopWebApplication.Controllers
  isExternal: false
  name: TicketShopWebApplication.Controllers
  nameWithType: TicketShopWebApplication.Controllers
  fullName: TicketShopWebApplication.Controllers
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Controllers.HomeController.Index*
  commentId: Overload:TicketShopWebApplication.Controllers.HomeController.Index
  isExternal: false
  name: Index
  nameWithType: HomeController.Index
  fullName: TicketShopWebApplication.Controllers.HomeController.Index
- uid: ActionResult
  isExternal: true
  name: ActionResult
  nameWithType: ActionResult
  fullName: ActionResult
- uid: TicketShopWebApplication.Controllers.HomeController.Details*
  commentId: Overload:TicketShopWebApplication.Controllers.HomeController.Details
  isExternal: false
  name: Details
  nameWithType: HomeController.Details
  fullName: TicketShopWebApplication.Controllers.HomeController.Details
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: TicketShopWebApplication.Controllers.HomeController.Create*
  commentId: Overload:TicketShopWebApplication.Controllers.HomeController.Create
  isExternal: false
  name: Create
  nameWithType: HomeController.Create
  fullName: TicketShopWebApplication.Controllers.HomeController.Create
- uid: IFormCollection
  isExternal: true
  name: IFormCollection
  nameWithType: IFormCollection
  fullName: IFormCollection
- uid: TicketShopWebApplication.Controllers.HomeController.Edit*
  commentId: Overload:TicketShopWebApplication.Controllers.HomeController.Edit
  isExternal: false
  name: Edit
  nameWithType: HomeController.Edit
  fullName: TicketShopWebApplication.Controllers.HomeController.Edit
- uid: TicketShopWebApplication.Controllers.HomeController.Delete*
  commentId: Overload:TicketShopWebApplication.Controllers.HomeController.Delete
  isExternal: false
  name: Delete
  nameWithType: HomeController.Delete
  fullName: TicketShopWebApplication.Controllers.HomeController.Delete
