### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.ErrorModel
  commentId: T:TicketShopWebApplication.Pages.ErrorModel
  id: ErrorModel
  parent: TicketShopWebApplication.Pages
  children:
  - TicketShopWebApplication.Pages.ErrorModel.OnGet
  - TicketShopWebApplication.Pages.ErrorModel.RequestId
  - TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
  langs:
  - csharp
  - vb
  name: ErrorModel
  nameWithType: ErrorModel
  fullName: TicketShopWebApplication.Pages.ErrorModel
  type: Class
  source:
    id: ErrorModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Error.cshtml.cs
    startLine: 9
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: 'public class ErrorModel : PageModel'
    content.vb: >-
      Public Class ErrorModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.ErrorModel.RequestId
  commentId: P:TicketShopWebApplication.Pages.ErrorModel.RequestId
  id: RequestId
  parent: TicketShopWebApplication.Pages.ErrorModel
  langs:
  - csharp
  - vb
  name: RequestId
  nameWithType: ErrorModel.RequestId
  fullName: TicketShopWebApplication.Pages.ErrorModel.RequestId
  type: Property
  source:
    id: RequestId
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Error.cshtml.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: public string RequestId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property RequestId As String
  overload: TicketShopWebApplication.Pages.ErrorModel.RequestId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
  commentId: P:TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
  id: ShowRequestId
  parent: TicketShopWebApplication.Pages.ErrorModel
  langs:
  - csharp
  - vb
  name: ShowRequestId
  nameWithType: ErrorModel.ShowRequestId
  fullName: TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
  type: Property
  source:
    id: ShowRequestId
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Error.cshtml.cs
    startLine: 13
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: public bool ShowRequestId { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property ShowRequestId As Boolean
  overload: TicketShopWebApplication.Pages.ErrorModel.ShowRequestId*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: TicketShopWebApplication.Pages.ErrorModel.OnGet
  commentId: M:TicketShopWebApplication.Pages.ErrorModel.OnGet
  id: OnGet
  parent: TicketShopWebApplication.Pages.ErrorModel
  langs:
  - csharp
  - vb
  name: OnGet()
  nameWithType: ErrorModel.OnGet()
  fullName: TicketShopWebApplication.Pages.ErrorModel.OnGet()
  type: Method
  source:
    id: OnGet
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Error.cshtml.cs
    startLine: 15
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: public void OnGet()
    content.vb: Public Sub OnGet
  overload: TicketShopWebApplication.Pages.ErrorModel.OnGet*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages
  commentId: N:TicketShopWebApplication.Pages
  isExternal: false
  name: TicketShopWebApplication.Pages
  nameWithType: TicketShopWebApplication.Pages
  fullName: TicketShopWebApplication.Pages
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.ErrorModel.RequestId*
  commentId: Overload:TicketShopWebApplication.Pages.ErrorModel.RequestId
  isExternal: false
  name: RequestId
  nameWithType: ErrorModel.RequestId
  fullName: TicketShopWebApplication.Pages.ErrorModel.RequestId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.ErrorModel.ShowRequestId*
  commentId: Overload:TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
  isExternal: false
  name: ShowRequestId
  nameWithType: ErrorModel.ShowRequestId
  fullName: TicketShopWebApplication.Pages.ErrorModel.ShowRequestId
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: TicketShopWebApplication.Pages.ErrorModel.OnGet*
  commentId: Overload:TicketShopWebApplication.Pages.ErrorModel.OnGet
  isExternal: false
  name: OnGet
  nameWithType: ErrorModel.OnGet
  fullName: TicketShopWebApplication.Pages.ErrorModel.OnGet
