### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Data.ApplicationDbContext
  commentId: T:TicketShopWebApplication.Data.ApplicationDbContext
  id: ApplicationDbContext
  parent: TicketShopWebApplication.Data
  children:
  - TicketShopWebApplication.Data.ApplicationDbContext.#ctor(DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext})
  - TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating(ModelBuilder)
  langs:
  - csharp
  - vb
  name: ApplicationDbContext
  nameWithType: ApplicationDbContext
  fullName: TicketShopWebApplication.Data.ApplicationDbContext
  type: Class
  source:
    id: ApplicationDbContext
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\ApplicationDbContext.cs
    startLine: 9
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data
  syntax:
    content: 'public class ApplicationDbContext : IdentityDbContext<ApplicationUser>'
    content.vb: >-
      Public Class ApplicationDbContext
          Inherits IdentityDbContext(Of ApplicationUser)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Data.ApplicationDbContext.#ctor(DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext})
  commentId: M:TicketShopWebApplication.Data.ApplicationDbContext.#ctor(DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext})
  id: '#ctor(DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext})'
  parent: TicketShopWebApplication.Data.ApplicationDbContext
  langs:
  - csharp
  - vb
  name: ApplicationDbContext(DbContextOptions<ApplicationDbContext>)
  nameWithType: ApplicationDbContext.ApplicationDbContext(DbContextOptions<ApplicationDbContext>)
  fullName: TicketShopWebApplication.Data.ApplicationDbContext.ApplicationDbContext(DbContextOptions<TicketShopWebApplication.Data.ApplicationDbContext>)
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\ApplicationDbContext.cs
    startLine: 11
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data
  syntax:
    content: public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
    parameters:
    - id: options
      type: DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext}
    content.vb: Public Sub New(options As DbContextOptions(Of ApplicationDbContext))
  overload: TicketShopWebApplication.Data.ApplicationDbContext.#ctor*
  nameWithType.vb: ApplicationDbContext.ApplicationDbContext(DbContextOptions(Of ApplicationDbContext))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: TicketShopWebApplication.Data.ApplicationDbContext.ApplicationDbContext(DbContextOptions(Of TicketShopWebApplication.Data.ApplicationDbContext))
  name.vb: ApplicationDbContext(DbContextOptions(Of ApplicationDbContext))
- uid: TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating(ModelBuilder)
  commentId: M:TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating(ModelBuilder)
  id: OnModelCreating(ModelBuilder)
  parent: TicketShopWebApplication.Data.ApplicationDbContext
  langs:
  - csharp
  - vb
  name: OnModelCreating(ModelBuilder)
  nameWithType: ApplicationDbContext.OnModelCreating(ModelBuilder)
  fullName: TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating(ModelBuilder)
  type: Method
  source:
    id: OnModelCreating
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Data\ApplicationDbContext.cs
    startLine: 16
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Data
  syntax:
    content: protected override void OnModelCreating(ModelBuilder builder)
    parameters:
    - id: builder
      type: ModelBuilder
    content.vb: Protected Overrides Sub OnModelCreating(builder As ModelBuilder)
  overload: TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
references:
- uid: TicketShopWebApplication.Data
  commentId: N:TicketShopWebApplication.Data
  isExternal: false
  name: TicketShopWebApplication.Data
  nameWithType: TicketShopWebApplication.Data
  fullName: TicketShopWebApplication.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Data.ApplicationDbContext.#ctor*
  commentId: Overload:TicketShopWebApplication.Data.ApplicationDbContext.#ctor
  isExternal: false
  name: ApplicationDbContext
  nameWithType: ApplicationDbContext.ApplicationDbContext
  fullName: TicketShopWebApplication.Data.ApplicationDbContext.ApplicationDbContext
- uid: DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext}
  commentId: '!:DbContextOptions{TicketShopWebApplication.Data.ApplicationDbContext}'
  definition: DbContextOptions`1
  name: DbContextOptions<ApplicationDbContext>
  nameWithType: DbContextOptions<ApplicationDbContext>
  fullName: DbContextOptions<TicketShopWebApplication.Data.ApplicationDbContext>
  nameWithType.vb: DbContextOptions(Of ApplicationDbContext)
  fullName.vb: DbContextOptions(Of TicketShopWebApplication.Data.ApplicationDbContext)
  name.vb: DbContextOptions(Of ApplicationDbContext)
  spec.csharp:
  - uid: DbContextOptions`1
    name: DbContextOptions
    nameWithType: DbContextOptions
    fullName: DbContextOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Data.ApplicationDbContext
    name: ApplicationDbContext
    nameWithType: ApplicationDbContext
    fullName: TicketShopWebApplication.Data.ApplicationDbContext
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: DbContextOptions`1
    name: DbContextOptions
    nameWithType: DbContextOptions
    fullName: DbContextOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Data.ApplicationDbContext
    name: ApplicationDbContext
    nameWithType: ApplicationDbContext
    fullName: TicketShopWebApplication.Data.ApplicationDbContext
  - name: )
    nameWithType: )
    fullName: )
- uid: DbContextOptions`1
  commentId: '!:DbContextOptions`1'
  isExternal: true
  name: DbContextOptions<>
  nameWithType: DbContextOptions<>
  fullName: DbContextOptions<>
  nameWithType.vb: DbContextOptions(Of )
  fullName.vb: DbContextOptions(Of )
  name.vb: DbContextOptions(Of )
  spec.csharp:
  - uid: DbContextOptions`1
    name: DbContextOptions
    nameWithType: DbContextOptions
    fullName: DbContextOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: DbContextOptions`1
    name: DbContextOptions
    nameWithType: DbContextOptions
    fullName: DbContextOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating*
  commentId: Overload:TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating
  isExternal: false
  name: OnModelCreating
  nameWithType: ApplicationDbContext.OnModelCreating
  fullName: TicketShopWebApplication.Data.ApplicationDbContext.OnModelCreating
- uid: ModelBuilder
  isExternal: true
  name: ModelBuilder
  nameWithType: ModelBuilder
  fullName: ModelBuilder
