### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.AboutModel
  commentId: T:TicketShopWebApplication.Pages.AboutModel
  id: AboutModel
  parent: TicketShopWebApplication.Pages
  children:
  - TicketShopWebApplication.Pages.AboutModel.Message
  - TicketShopWebApplication.Pages.AboutModel.OnGet
  langs:
  - csharp
  - vb
  name: AboutModel
  nameWithType: AboutModel
  fullName: TicketShopWebApplication.Pages.AboutModel
  type: Class
  source:
    id: AboutModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\About.cshtml.cs
    startLine: 8
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: 'public class AboutModel : PageModel'
    content.vb: >-
      Public Class AboutModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.AboutModel.Message
  commentId: P:TicketShopWebApplication.Pages.AboutModel.Message
  id: Message
  parent: TicketShopWebApplication.Pages.AboutModel
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: AboutModel.Message
  fullName: TicketShopWebApplication.Pages.AboutModel.Message
  type: Property
  source:
    id: Message
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\About.cshtml.cs
    startLine: 10
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: public string Message { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Message As String
  overload: TicketShopWebApplication.Pages.AboutModel.Message*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.AboutModel.OnGet
  commentId: M:TicketShopWebApplication.Pages.AboutModel.OnGet
  id: OnGet
  parent: TicketShopWebApplication.Pages.AboutModel
  langs:
  - csharp
  - vb
  name: OnGet()
  nameWithType: AboutModel.OnGet()
  fullName: TicketShopWebApplication.Pages.AboutModel.OnGet()
  type: Method
  source:
    id: OnGet
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\About.cshtml.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages
  syntax:
    content: public void OnGet()
    content.vb: Public Sub OnGet
  overload: TicketShopWebApplication.Pages.AboutModel.OnGet*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages
  commentId: N:TicketShopWebApplication.Pages
  isExternal: false
  name: TicketShopWebApplication.Pages
  nameWithType: TicketShopWebApplication.Pages
  fullName: TicketShopWebApplication.Pages
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.AboutModel.Message*
  commentId: Overload:TicketShopWebApplication.Pages.AboutModel.Message
  isExternal: false
  name: Message
  nameWithType: AboutModel.Message
  fullName: TicketShopWebApplication.Pages.AboutModel.Message
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TicketShopWebApplication.Pages.AboutModel.OnGet*
  commentId: Overload:TicketShopWebApplication.Pages.AboutModel.OnGet
  isExternal: false
  name: OnGet
  nameWithType: AboutModel.OnGet
  fullName: TicketShopWebApplication.Pages.AboutModel.OnGet
