### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Controllers
  commentId: N:TicketShopWebApplication.Controllers
  id: TicketShopWebApplication.Controllers
  children:
  - TicketShopWebApplication.Controllers.AccountController
  - TicketShopWebApplication.Controllers.HomeController
  langs:
  - csharp
  - vb
  name: TicketShopWebApplication.Controllers
  nameWithType: TicketShopWebApplication.Controllers
  fullName: TicketShopWebApplication.Controllers
  type: Namespace
  assemblies:
  - TicketShopWebApplication
references:
- uid: TicketShopWebApplication.Controllers.AccountController
  commentId: T:TicketShopWebApplication.Controllers.AccountController
  isExternal: false
  name: AccountController
  nameWithType: AccountController
  fullName: TicketShopWebApplication.Controllers.AccountController
- uid: TicketShopWebApplication.Controllers.HomeController
  commentId: T:TicketShopWebApplication.Controllers.HomeController
  isExternal: false
  name: HomeController
  nameWithType: HomeController
  fullName: TicketShopWebApplication.Controllers.HomeController
