### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordModel
  id: ResetPasswordModel
  parent: TicketShopWebApplication.Pages.Account
  children:
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser})
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet(System.String)
  - TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync
  langs:
  - csharp
  - vb
  name: ResetPasswordModel
  nameWithType: ResetPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  type: Class
  source:
    id: ResetPasswordModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: 'public class ResetPasswordModel : PageModel'
    content.vb: >-
      Public Class ResetPasswordModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser})
  commentId: M:TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser})
  id: '#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser})'
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  langs:
  - csharp
  - vb
  name: ResetPasswordModel(UserManager<ApplicationUser>)
  nameWithType: ResetPasswordModel.ResetPasswordModel(UserManager<ApplicationUser>)
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.ResetPasswordModel(UserManager<TicketShopWebApplication.Data.ApplicationUser>)
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 16
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public ResetPasswordModel(UserManager<ApplicationUser> userManager)
    parameters:
    - id: userManager
      type: UserManager{TicketShopWebApplication.Data.ApplicationUser}
    content.vb: Public Sub New(userManager As UserManager(Of ApplicationUser))
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor*
  nameWithType.vb: ResetPasswordModel.ResetPasswordModel(UserManager(Of ApplicationUser))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: TicketShopWebApplication.Pages.Account.ResetPasswordModel.ResetPasswordModel(UserManager(Of TicketShopWebApplication.Data.ApplicationUser))
  name.vb: ResetPasswordModel(UserManager(Of ApplicationUser))
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
  commentId: P:TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
  id: Input
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  langs:
  - csharp
  - vb
  name: Input
  nameWithType: ResetPasswordModel.Input
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
  type: Property
  source:
    id: Input
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 21
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public ResetPasswordModel.InputModel Input { get; set; }
    parameters: []
    return:
      type: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
    content.vb: Public Property Input As ResetPasswordModel.InputModel
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet(System.String)
  commentId: M:TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet(System.String)
  id: OnGet(System.String)
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  langs:
  - csharp
  - vb
  name: OnGet(String)
  nameWithType: ResetPasswordModel.OnGet(String)
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet(System.String)
  type: Method
  source:
    id: OnGet
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 43
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public IActionResult OnGet(string code = null)
    parameters:
    - id: code
      type: System.String
    return:
      type: IActionResult
    content.vb: Public Function OnGet(code As String = Nothing) As IActionResult
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync
  commentId: M:TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync
  id: OnPostAsync
  parent: TicketShopWebApplication.Pages.Account.ResetPasswordModel
  langs:
  - csharp
  - vb
  name: OnPostAsync()
  nameWithType: ResetPasswordModel.OnPostAsync()
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync()
  type: Method
  source:
    id: OnPostAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\ResetPassword.cshtml.cs
    startLine: 59
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account
  syntax:
    content: public Task<IActionResult> OnPostAsync()
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnPostAsync As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account
  commentId: N:TicketShopWebApplication.Pages.Account
  isExternal: false
  name: TicketShopWebApplication.Pages.Account
  nameWithType: TicketShopWebApplication.Pages.Account
  fullName: TicketShopWebApplication.Pages.Account
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.#ctor
  isExternal: false
  name: ResetPasswordModel
  nameWithType: ResetPasswordModel.ResetPasswordModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.ResetPasswordModel
- uid: UserManager{TicketShopWebApplication.Data.ApplicationUser}
  commentId: '!:UserManager{TicketShopWebApplication.Data.ApplicationUser}'
  definition: UserManager`1
  name: UserManager<ApplicationUser>
  nameWithType: UserManager<ApplicationUser>
  fullName: UserManager<TicketShopWebApplication.Data.ApplicationUser>
  nameWithType.vb: UserManager(Of ApplicationUser)
  fullName.vb: UserManager(Of TicketShopWebApplication.Data.ApplicationUser)
  name.vb: UserManager(Of ApplicationUser)
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: )
    nameWithType: )
    fullName: )
- uid: UserManager`1
  isExternal: true
  name: UserManager<>
  nameWithType: UserManager<>
  fullName: UserManager<>
  nameWithType.vb: UserManager(Of )
  fullName.vb: UserManager(Of )
  name.vb: UserManager(Of )
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
  isExternal: false
  name: Input
  nameWithType: ResetPasswordModel.Input
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.Input
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  commentId: T:TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
  parent: TicketShopWebApplication.Pages.Account
  isExternal: false
  name: ResetPasswordModel.InputModel
  nameWithType: ResetPasswordModel.InputModel
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.InputModel
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet
  isExternal: false
  name: OnGet
  nameWithType: ResetPasswordModel.OnGet
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnGet
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: IActionResult
  isExternal: true
  name: IActionResult
  nameWithType: IActionResult
  fullName: IActionResult
- uid: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync
  isExternal: false
  name: OnPostAsync
  nameWithType: ResetPasswordModel.OnPostAsync
  fullName: TicketShopWebApplication.Pages.Account.ResetPasswordModel.OnPostAsync
- uid: Task{IActionResult}
  commentId: '!:Task{IActionResult}'
  definition: Task`1
  name: Task<IActionResult>
  nameWithType: Task<IActionResult>
  fullName: Task<IActionResult>
  nameWithType.vb: Task(Of IActionResult)
  fullName.vb: Task(Of IActionResult)
  name.vb: Task(Of IActionResult)
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Task`1
  isExternal: true
  name: Task<>
  nameWithType: Task<>
  fullName: Task<>
  nameWithType.vb: Task(Of )
  fullName.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
