### YamlMime:ManagedReference
items:
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  commentId: T:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  id: GenerateRecoveryCodesModel
  parent: TicketShopWebApplication.Pages.Account.Manage
  children:
  - TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel})
  - TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync
  - TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync
  langs:
  - csharp
  - vb
  name: GenerateRecoveryCodesModel
  nameWithType: GenerateRecoveryCodesModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  type: Class
  source:
    id: GenerateRecoveryCodesModel
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.cs
    startLine: 12
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: 'public class GenerateRecoveryCodesModel : PageModel'
    content.vb: >-
      Public Class GenerateRecoveryCodesModel
          Inherits PageModel
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel})
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel})
  id: '#ctor(UserManager{TicketShopWebApplication.Data.ApplicationUser},ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel})'
  parent: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  langs:
  - csharp
  - vb
  name: GenerateRecoveryCodesModel(UserManager<ApplicationUser>, ILogger<GenerateRecoveryCodesModel>)
  nameWithType: GenerateRecoveryCodesModel.GenerateRecoveryCodesModel(UserManager<ApplicationUser>, ILogger<GenerateRecoveryCodesModel>)
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.GenerateRecoveryCodesModel(UserManager<TicketShopWebApplication.Data.ApplicationUser>, ILogger<TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel>)
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.cs
    startLine: 17
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public GenerateRecoveryCodesModel(UserManager<ApplicationUser> userManager, ILogger<GenerateRecoveryCodesModel> logger)
    parameters:
    - id: userManager
      type: UserManager{TicketShopWebApplication.Data.ApplicationUser}
    - id: logger
      type: ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel}
    content.vb: Public Sub New(userManager As UserManager(Of ApplicationUser), logger As ILogger(Of GenerateRecoveryCodesModel))
  overload: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor*
  nameWithType.vb: GenerateRecoveryCodesModel.GenerateRecoveryCodesModel(UserManager(Of ApplicationUser), ILogger(Of GenerateRecoveryCodesModel))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.GenerateRecoveryCodesModel(UserManager(Of TicketShopWebApplication.Data.ApplicationUser), ILogger(Of TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel))
  name.vb: GenerateRecoveryCodesModel(UserManager(Of ApplicationUser), ILogger(Of GenerateRecoveryCodesModel))
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync
  id: OnGetAsync
  parent: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  langs:
  - csharp
  - vb
  name: OnGetAsync()
  nameWithType: GenerateRecoveryCodesModel.OnGetAsync()
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync()
  type: Method
  source:
    id: OnGetAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.cs
    startLine: 25
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public Task<IActionResult> OnGetAsync()
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnGetAsync As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync
  commentId: M:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync
  id: OnPostAsync
  parent: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  langs:
  - csharp
  - vb
  name: OnPostAsync()
  nameWithType: GenerateRecoveryCodesModel.OnPostAsync()
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync()
  type: Method
  source:
    id: OnPostAsync
    path: C:\Users\Adriana\Documents\GitHub\ticketSystem-team-terminator\src\TicketShopWebApplication\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.cs
    startLine: 41
  assemblies:
  - TicketShopWebApplication
  namespace: TicketShopWebApplication.Pages.Account.Manage
  syntax:
    content: public Task<IActionResult> OnPostAsync()
    return:
      type: Task{IActionResult}
    content.vb: Public Function OnPostAsync As Task(Of IActionResult)
  overload: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TicketShopWebApplication.Pages.Account.Manage
  commentId: N:TicketShopWebApplication.Pages.Account.Manage
  isExternal: false
  name: TicketShopWebApplication.Pages.Account.Manage
  nameWithType: TicketShopWebApplication.Pages.Account.Manage
  fullName: TicketShopWebApplication.Pages.Account.Manage
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.#ctor
  isExternal: false
  name: GenerateRecoveryCodesModel
  nameWithType: GenerateRecoveryCodesModel.GenerateRecoveryCodesModel
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.GenerateRecoveryCodesModel
- uid: UserManager{TicketShopWebApplication.Data.ApplicationUser}
  commentId: '!:UserManager{TicketShopWebApplication.Data.ApplicationUser}'
  definition: UserManager`1
  name: UserManager<ApplicationUser>
  nameWithType: UserManager<ApplicationUser>
  fullName: UserManager<TicketShopWebApplication.Data.ApplicationUser>
  nameWithType.vb: UserManager(Of ApplicationUser)
  fullName.vb: UserManager(Of TicketShopWebApplication.Data.ApplicationUser)
  name.vb: UserManager(Of ApplicationUser)
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Data.ApplicationUser
    name: ApplicationUser
    nameWithType: ApplicationUser
    fullName: TicketShopWebApplication.Data.ApplicationUser
  - name: )
    nameWithType: )
    fullName: )
- uid: ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel}
  commentId: '!:ILogger{TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel}'
  definition: ILogger`1
  name: ILogger<GenerateRecoveryCodesModel>
  nameWithType: ILogger<GenerateRecoveryCodesModel>
  fullName: ILogger<TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel>
  nameWithType.vb: ILogger(Of GenerateRecoveryCodesModel)
  fullName.vb: ILogger(Of TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel)
  name.vb: ILogger(Of GenerateRecoveryCodesModel)
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
    name: GenerateRecoveryCodesModel
    nameWithType: GenerateRecoveryCodesModel
    fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
    name: GenerateRecoveryCodesModel
    nameWithType: GenerateRecoveryCodesModel
    fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel
  - name: )
    nameWithType: )
    fullName: )
- uid: UserManager`1
  isExternal: true
  name: UserManager<>
  nameWithType: UserManager<>
  fullName: UserManager<>
  nameWithType.vb: UserManager(Of )
  fullName.vb: UserManager(Of )
  name.vb: UserManager(Of )
  spec.csharp:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UserManager`1
    name: UserManager
    nameWithType: UserManager
    fullName: UserManager
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: ILogger`1
  isExternal: true
  name: ILogger<>
  nameWithType: ILogger<>
  fullName: ILogger<>
  nameWithType.vb: ILogger(Of )
  fullName.vb: ILogger(Of )
  name.vb: ILogger(Of )
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync
  isExternal: false
  name: OnGetAsync
  nameWithType: GenerateRecoveryCodesModel.OnGetAsync
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnGetAsync
- uid: Task{IActionResult}
  commentId: '!:Task{IActionResult}'
  definition: Task`1
  name: Task<IActionResult>
  nameWithType: Task<IActionResult>
  fullName: Task<IActionResult>
  nameWithType.vb: Task(Of IActionResult)
  fullName.vb: Task(Of IActionResult)
  name.vb: Task(Of IActionResult)
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IActionResult
    name: IActionResult
    nameWithType: IActionResult
    fullName: IActionResult
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Task`1
  isExternal: true
  name: Task<>
  nameWithType: Task<>
  fullName: Task<>
  nameWithType.vb: Task(Of )
  fullName.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    nameWithType: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync*
  commentId: Overload:TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync
  isExternal: false
  name: OnPostAsync
  nameWithType: GenerateRecoveryCodesModel.OnPostAsync
  fullName: TicketShopWebApplication.Pages.Account.Manage.GenerateRecoveryCodesModel.OnPostAsync
